alias nvim="~/.config/nvim-macos/bin/nvim"
alias cls="clear"
alias python="python3"
alias cda="conda activate $1"
alias cde="conda deactivate"
alias kc="kubectl"
alias eks="eksctl"
alias zrc="nvim ~/.zshrc"
alias nv="cd ~/.config/nvim"
alias src="source ~/.zshrc"

export PATH="$HOME/.local/bin/:$HOME/.config/nvim-macos/bin/:$PATH"
eval "$(zoxide init --cmd cd zsh)"
